# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base:3.19"
  amd64: "ghcr.io/home-assistant/amd64-base:3.19"
  armv7: "ghcr.io/home-assistant/armv7-base:3.19"
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: Ventilairsec2HA"
  org.opencontainers.image.description: "Addon pour contrôler une VMI Purevent Ventilairsec via EnOcean"
  org.opencontainers.image.source: "https://github.com/ricolaflo88/Ventilairsec2HA"
  org.opencontainers.image.licenses: "MIT"
args:
  TEMPIO_VERSION: "2021.09.0"
